# Generated by Django 2.1.7 on 2019-03-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=10)),
                ('guideline_type', models.CharField(max_length=13)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
