# Generated by Django 2.1.7 on 2019-03-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0002_auto_20190326_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='key_indicator_PSI',
            new_name='PSI',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='key_indicator_estimateStartingTime',
            new_name='estimated_starting_time',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='key_indicator_numOfInjured',
            new_name='number_of_death',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='key_indicator_numOfdeaths',
            new_name='number_of_injured',
        ),
    ]
