# Generated by Django 2.1.7 on 2019-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0003_auto_20190326_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='incident_assistanceRequired',
            field=models.CharField(choices=[('emergencyAmbulance', 'Emergency Ambulance'), ('rescueEvacuation', 'Rescue Evacuation'), ('none', 'None')], default='none', max_length=20),
        ),
    ]
