# Generated by Django 2.1.7 on 2019-03-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0004_auto_20190326_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='PSI',
            new_name='pollutant_standards_index',
        ),
    ]
