# Generated by Django 2.1.7 on 2019-03-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0005_auto_20190326_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='report_person_region',
            new_name='incident_region',
        ),
    ]
