# Generated by Django 2.1.7 on 2019-03-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccs', '0006_auto_20190326_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='incident_assistanceRequired',
            new_name='incident_assistance_required',
        ),
    ]
